name: Tests for voroqh and quickhull

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build QuickHull tests
      working-directory: src/voroqh/quickhull/Tests
      run: cmake -S . -B build && cmake --build build
    - name: run QuickHull tests 
      working-directory: src/voroqh/quickhull/Tests
      run: ./build/QuickHullTests
    - name: build voroqh tests
      working-directory: src/voroqh
      run: g++ -std=c++17 -O3 tests.cpp voronoi.cpp -o voroqh_tests
    - name: run voroqh tests
      working-directory: src/voroqh
      run: ./voroqh_tests
